spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupang
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: https://5ea8b8f1ab584d4795f14b293ddda0bc.ap-northeast-2.aws.elastic-cloud.com:443
    username: elastic
    password: wq6QgAOI0khpSH7qBp2FqTM8

logging:
  level:
    org.elasticsearch.client: TRACE