[db]
database = "postgres"
url = "postgres://root:1234@localhost:5433/litdb?sslmode=disable"

[kafka]
urls = ["pkc-e82om.ap-northeast-2.aws.confluent.cloud:9092"]
APIKey = "KXUFDPMD56HECEL6"
secret = "cfltHngHaNiIa+QEp5uZjQhQwbisBH8HIFJqtrDh97sdwHO2U6efOpFDAnB5FqEw"
clientId = "ccloud-go-client-65fad313-91b8-4017-99e7-41d177654321"