services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 9200:9200
    environment:
      # 아래 설정은 개발/테스트 환경에서 간단하게 테스트하기 위한 옵션 (운영 환경x)
      - discovery.type=single-node # 단일 노드
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200 # kibana가 통신할 Elasticsearch 주소
