[network]
port  = ":8080"

[authenticator]
secret ="JBSWY3DPEHPK3PXP"
issuer = "test"
account = "man"
fileName = "qr.PNG"

[db]
database = "mysql"
url = "root:1234@tcp(localhost:3306)/Scrapping?multiStatements=true&parseTime=true"